re_blockquote = "<div class=\"bbc-block[^\"]*?\">(\n|.)*?(</block.*?>)?</div>"
re_br = "<br/>"
re_embed_images = "src.+//.*?\.?(.+\.\w{2,4})/?.*?/([^/]+)\.(\w{2,4})"
re_embed_videos = "https://([^\"]+\.\w{2,4})/([^/]+)\.mp4"
re_twitter = "\w{4,5}://([^/]+)/([^/]+)/status/(\d+)\?[^/<]"
re_youtube = "\w{4,5}://([^/]+)/embed/([^?]+)"
re_fpp = "/([^\'/]+)[/']{1,2}([^\'/]*?)([/']{1,2})?([^\'/]*?)"
re_bl = "banlist\.php[^>]+"
re_bl_user = "userid=(\d+)"
re_bl_post = "frompost(\d+)"
re_bl_appr = "adminid=(\d*)"
re_th = "\"(http.+?forums.somethingawful.com[^>]+showthread.php\?[^\"]*?)\""
re_prof = "<.*(member\.php[^>]*\")>"
re_fr = "(\w+://(www\.)?somethingawful\.com/?[^\"]*?/[^\"]*?/[^\"]*?/?)"
re_sp = "<.*(dictionary\.php[^>]*?\")\s.*?>"
re_pg = "<.*(stats\.php[^>]*\")>"
re_userid = "user\w{1,2}=(\d+)"
re_username = "username=([^\"]+)"
re_post_datetime = "[A-Za-z]{3,4}\s\d{1,2},\s\d{4}\s\d{2}:\d{2}"
re_post_id = "\d+"
re_userid_leper = "\d{5,6}"
re_punish_length = "\d+\s(hours|hour|day|days|week|weeks|year|years)"
re_puid = "userid=(\d+)"
re_av = "<dd class=\"title.+?><img.+src=\"([^\"]+)\""
re_gt = "<img.+?\"(htt.+?)\".*?>"
re_pc = "<dt>Post Count</dt><dd>(-?\d+)</dd>"
re_pr = "<dt>Post Rate</dt><dd>(-?\d*\.?\d*?) per day</dd>"
re_lp = "<dt>Last Post</dt><dd>(.+)</dd>"
re_prr_txt = "[,.<>/?;:\"\\\[\]\{\}\-=_+|!@#$%^&*()`~]+?"
re_lastpage = "title=\"Last page\">(\d+)"
re_sub_tid = "\" id=\"thread(\d+)"